// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccountProfile(arg1) {
  return window['go']['accounts']['AccountService']['AddAccountProfile'](arg1);
}

export function CancelAccountAttachFlow(arg1) {
  return window['go']['accounts']['AccountService']['CancelAccountAttachFlow'](arg1);
}

export function CheckAllSessionStatuses() {
  return window['go']['accounts']['AccountService']['CheckAllSessionStatuses']();
}

export function CheckSessionStatus(arg1) {
  return window['go']['accounts']['AccountService']['CheckSessionStatus'](arg1);
}

export function CompleteAccountAttachFlow(arg1, arg2) {
  return window['go']['accounts']['AccountService']['CompleteAccountAttachFlow'](arg1, arg2);
}

export function GetAttachFlowStatus(arg1) {
  return window['go']['accounts']['AccountService']['GetAttachFlowStatus'](arg1);
}

export function GetDefaultAccount() {
  return window['go']['accounts']['AccountService']['GetDefaultAccount']();
}

export function ListAccounts() {
  return window['go']['accounts']['AccountService']['ListAccounts']();
}

export function RemoveAccount(arg1) {
  return window['go']['accounts']['AccountService']['RemoveAccount'](arg1);
}

export function SetDefaultAccount(arg1) {
  return window['go']['accounts']['AccountService']['SetDefaultAccount'](arg1);
}

export function StartAccountAttachFlow() {
  return window['go']['accounts']['AccountService']['StartAccountAttachFlow']();
}
