// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {accounts} from '../models';

export function AddAccountProfile(arg1:accounts.AccountProfile):Promise<Array<accounts.AccountProfile>>;

export function CancelAccountAttachFlow(arg1:string):Promise<void>;

export function CheckAllSessionStatuses():Promise<Array<accounts.AccountProfile>>;

export function CheckSessionStatus(arg1:string):Promise<Array<accounts.AccountProfile>>;

export function CompleteAccountAttachFlow(arg1:string,arg2:string):Promise<Array<accounts.AccountProfile>>;

export function GetAttachFlowStatus(arg1:string):Promise<accounts.AttachFlowStatusResponse>;

export function GetDefaultAccount():Promise<accounts.AccountProfile>;

export function ListAccounts():Promise<Array<accounts.AccountProfile>>;

export function RemoveAccount(arg1:string):Promise<Array<accounts.AccountProfile>>;

export function SetDefaultAccount(arg1:string):Promise<Array<accounts.AccountProfile>>;

export function StartAccountAttachFlow():Promise<accounts.AttachFlowStatusResponse>;
