// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractMedia(arg1) {
  return window['go']['crawl']['CrawlHandler']['ExtractMedia'](arg1);
}

export function ExtractPostsFromHTML(arg1) {
  return window['go']['crawl']['CrawlHandler']['ExtractPostsFromHTML'](arg1);
}

export function ExtractTextFromComet(arg1) {
  return window['go']['crawl']['CrawlHandler']['ExtractTextFromComet'](arg1);
}

export function FetchFriends(arg1, arg2, arg3) {
  return window['go']['crawl']['CrawlHandler']['FetchFriends'](arg1, arg2, arg3);
}

export function RunCrawl(arg1) {
  return window['go']['crawl']['CrawlHandler']['RunCrawl'](arg1);
}
