// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {crawl} from '../models';

export function ExtractMedia(arg1:any):Promise<Array<string>>;

export function ExtractPostsFromHTML(arg1:string):Promise<Array<crawl.CrawlPostEntity>>;

export function ExtractTextFromComet(arg1:Record<string, any>):Promise<string>;

export function RunCrawl(arg1:crawl.CrawlRequest):Promise<crawl.CrawlResponse>;
