// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {actiontest} from '../models';

export function GetActionLogs():Promise<Array<actiontest.ActionLog>>;

export function LikePost(arg1:actiontest.LikePostRequest):Promise<actiontest.LikePostResponse>;
