// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActionLogs() {
  return window['go']['actiontest']['ActionHandler']['GetActionLogs']();
}

export function GetReactDocID() {
  return window['go']['actiontest']['ActionHandler']['GetReactDocID']();
}

export function LikePost(arg1) {
  return window['go']['actiontest']['ActionHandler']['LikePost'](arg1);
}

export function UpdateReactDocID(arg1) {
  return window['go']['actiontest']['ActionHandler']['UpdateReactDocID'](arg1);
}
