// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommentPost(arg1) {
  return window['go']['actiontest']['ActionHandler']['CommentPost'](arg1);
}

export function CreatePost(arg1) {
  return window['go']['actiontest']['ActionHandler']['CreatePost'](arg1);
}

export function GetActionLogs() {
  return window['go']['actiontest']['ActionHandler']['GetActionLogs']();
}

export function GetCommentDocID() {
  return window['go']['actiontest']['ActionHandler']['GetCommentDocID']();
}

export function GetCreatePostDocID() {
  return window['go']['actiontest']['ActionHandler']['GetCreatePostDocID']();
}

export function GetReactDocID() {
  return window['go']['actiontest']['ActionHandler']['GetReactDocID']();
}

export function GetScrapeDocID() {
  return window['go']['actiontest']['ActionHandler']['GetScrapeDocID']();
}

export function LikePost(arg1) {
  return window['go']['actiontest']['ActionHandler']['LikePost'](arg1);
}

export function UpdateCommentDocID(arg1) {
  return window['go']['actiontest']['ActionHandler']['UpdateCommentDocID'](arg1);
}

export function UpdateCreatePostDocID(arg1) {
  return window['go']['actiontest']['ActionHandler']['UpdateCreatePostDocID'](arg1);
}

export function UpdateReactDocID(arg1) {
  return window['go']['actiontest']['ActionHandler']['UpdateReactDocID'](arg1);
}

export function UpdateScrapeDocID(arg1) {
  return window['go']['actiontest']['ActionHandler']['UpdateScrapeDocID'](arg1);
}
