// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {actiontest} from '../models';

export function CommentPost(arg1:actiontest.CommentPostRequest):Promise<actiontest.CommentPostResponse>;

export function CreatePost(arg1:actiontest.CreatePostRequest):Promise<actiontest.CreatePostResponse>;

export function GetActionLogs():Promise<Array<actiontest.ActionLog>>;

export function GetCreatePostDocID():Promise<string>;

export function GetReactDocID():Promise<string>;

export function LikePost(arg1:actiontest.LikePostRequest):Promise<actiontest.LikePostResponse>;

export function UpdateCreatePostDocID(arg1:string):Promise<string>;

export function UpdateReactDocID(arg1:string):Promise<string>;
