// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {actiontest} from '../models';

export function GetSessionStatus():Promise<actiontest.SessionStatus>;
